
namespace ViewModels

    class BusySpinner extends ViewModel

        override function template() as object

            ' There are 2 spinner implemented accoding to design. Both have the same controller.
            context = {
                afterWidgetMounted: sub(widget)
                    widget.visible = true
                    widget.control = "stop"
                end sub,
                beforeWidgetDestroy: sub(widget)
                    widget.visible = false
                    widget.control = "stop"
                end sub
            }

            return {
                id: "defaultSpinner",
                sgName: "BusySpinner",
                theme: "busySpinner",
                fields: {
                    uri: "@context.theme.busySpinner.url",
                    width: "@context.theme.busySpinner.size.w",
                    height: "@context.theme.busySpinner.size.h",
                    visible: true
                },
                context: context,
                children: {
                    id: "innerSpinner",
                    sgName: "BusySpinner",
                    fields: {
                        uri: "#theme.busySpinner.url",
                        translation: [4, 4],
                        clockwise: false,
                        opacity: 0.5,
                        spinInterval: 0.8,
                        visible: true,
                        translation: [4, 4],
                        width: function(widget)
                            return widget.context.theme.busySpinner.size.w - 8
                        end function,
                        height: function(widget)
                            return widget.context.theme.busySpinner.size.h - 8
                        end function
                    },
                    context: context
                }
            }
        end function

    end class
end namespace
