
namespace ViewModels

    class BusySpinner extends ViewModel

        override function template() as object

            ' There are 2 spinner implemented accoding to design. Both have the same controller.
            return {
                id: "defaultSpinner",
                sgName: "BusySpinner",
                theme: "busySpinner",
                fields: {
                    uri: "@context.theme.busySpinner.url",
                    width: "@context.theme.busySpinner.size.w",
                    height: "@context.theme.busySpinner.size.h",
                    visible: true
                },
                onMountWidget: sub()
                    m.node.visible = true
                    m.node.control = "stop"
                end sub,
                onDestroyWidget: sub()
                    m.node.visible = false
                    m.node.control = "stop"
                end sub,
                children: {
                    id: "innerSpinner",
                    sgName: "BusySpinner",
                    fields: {
                        uri: "#theme.busySpinner.url",
                        clockwise: false,
                        opacity: 0.5,
                        spinInterval: 0.8,
                        visible: true,
                        translation: [10, 10],
                        scale: function(widget)
                            scale = (widget.context.theme.busySpinner.size.w - 20) / widget.context.theme.busySpinner.size.w
                            return [
                                scale,
                                scale
                            ]
                        end function
                    },
                    onMountWidget: sub()
                        m.node.visible = true
                        m.node.control = "stop"
                    end sub,
                    onDestroyWidget: sub()
                        m.node.visible = false
                        m.node.control = "stop"
                    end sub
                }
            }
        end function

    end class
end namespace
