
' Framework
import "pkg:/source/libs/rotorFramework/RotorFramework.bs"

' Import assets
import "pkg:/assets/design/generated/theme.brs"
import "pkg:/assets/design/generated/translation.brs"

' constants
import "pkg:/components/app/common/intentTypes.bs"

' Import Views
import "../viewModels/busySpinner/busySpinner.bs"
import "../viewModels/buttons/simpleButton.bs"
import "../viewModels/layout/layout.bs"
import "../viewModels/loadingScreen/loadingScreen.bs"
import "../viewModels/optionList/optionList.bs"
import "../viewModels/pageMenu/pageMenu.bs"
import "../viewModels/pageMenu/pageMenuItem.bs"
import "../viewModels/pages/basePage.bs"
import "../viewModels/pages/home/homePage.bs"
import "../viewModels/pages/moviesPage.bs"
import "../viewModels/pages/zoomListSample/zoomListSamplePage.bs"
import "../viewModels/pages/playgroundPage.bs"
import "../viewModels/pages/seriesPage.bs"
import "../viewModels/pages/settings/languagePicker/languagePicker.bs"
import "../viewModels/pages/settings/languagePicker/languagePickerItem.bs"
import "../viewModels/pages/settings/settingsPage.bs"
import "../viewModels/pages/settings/settingWrapper.bs"
import "../viewModels/pages/settings/themePicker/themePicker.bs"
import "../viewModels/pages/settings/themePicker/themePickerItem.bs"



sub init()
    m.roDeviceInfo = CreateObject("roDeviceInfo")
end sub



sub initApplication(payload = {} as object)

    ' (1) Initialize Rotor Framework
    m.appFw = new Rotor.Framework({
        tasks: ["AppTask"],
        onTaskReady: onTaskReady, ' optional
        debug: {
            autoSetNodeId: true ' If true, you can find nodes in RALE much easier. (Available only in debug mode.)
        }
    })

    ' * REGISTER PLUGINS

    ' (2) Pluginize your ViewBuilder on demand
    m.appFw.registerPlugins([
        new Rotor.DynamicAssetContextPlugin("theme"),
        new Rotor.DynamicAssetContextPlugin("tr"),
        new Rotor.FieldsPlugin("fields"),
        new Rotor.FontStylePlugin("fontStyle"),
        new Rotor.FocusPlugin("focus")
        new Rotor.DispatcherProviderPlugin("dispatcher"),
        new Rotor.ObserverPlugin("observer"),
        new Rotor.OnReadyExpression("onReadyExpression"),
    ])


    '  (3) Create our first ViewModel using View Builder Engine
    ' Note that render calls are queued until the tasks are ready.
    m.appFw.render({
        id: "loadingScreen",
        viewModel: ViewModels.LoadingScreen,
        props: {
            shouldPreloadResources: true,
            shouldPrerenderPages: true
        }
    })

end sub


' Below optional callback function can be provided to be notified when the tasks are ready.
sub onTaskReady()
    ' Get user's theme and language preference
    m.usereDispatcher = m.appFw.getDispatcher("user")
    userState = m.usereDispatcher.getState()
    ' Set theme using theme plugin
    m.appFw.plugins.theme.setAssets(getAssets_theme()[userState.personalization.activeThemeKey])
    ' Set language using theme plugin
    m.appFw.plugins.tr.setAssets(getAssets_translation()[userState.personalization.activeLanguageKey])
end sub



function onKeyEvent(key as string, press as boolean) as boolean
    if press = true

        result = m.appFw.plugins.focus.onKeyEventHandler(key, press)

        if result.handled = true

            if result.isSelected = true
                ' additional handler
            end if
            return result.handled

        end if

    end if
    return false
end function


sub destroyApplication(payload as object)
    m.appFw.destroy()
end sub
