namespace Rotor

    class BaseWidget

        ' Public properties

        public id as string
        public children as object
        public parent as object

        public context as object ' local widget context
        public props as object ' props populated by viewModel
        public sgName as string ' rosgNode name
        public zIndex as integer

        public onMountWidget as function ' widget's lifecycle callback
        public onUpdateWidget as function ' widget's lifecycle callback
        public onDestroyWidget as function ' widget's lifecycle callback

        ' Public methods

        public getWidget as function
        public findWidgets as function
        public getChildrenWidgets as function
        public getSubtreeClone as function
        public render as function
        public erase as function
        public getDispatcher as function
        public animator as function
        public node as object

        ' Rotor engire properties

        HID as string ' used by rotor engine
        vmHID as string ' used by rotor engine
        isRootChild as boolean ' used by rotor engine
        childrenHIDhash as object ' used by rotor engine
        parentHID as string ' used by rotor engine
        isViewModel = false ' used by rotor engine

    end class

end namespace
