
class BasePage extends ViewModel

    override function template() as object
        return {
            focus: {
                group: {
                    forwardFocusId: "rowListExample",
                    back: "pageMenu"
                }
            },
            sgName: "Group",
            children: [
                {
                    id: "viewTitle",
                    sgName: "Label",
                    tr: "menuItems." + m.props.pageKey,
                    theme: "fontStyles.H2",
                    fontStyle: "@context.theme.fontStyles.H2",
                    fields: {
                        text: "@context.tr.menuItems." + m.props.pageKey + ".text"
                    }
                }
            ]
        }
    end function


end class
