namespace IntentType

    enum APP_STORE
        LOAD_REMOTE_APP_CONFIG = "app_load_remote_config"
        SET_ACTIVE_PAGE_KEY = "app_set_new_page_key"
    end enum

    enum PRELOADER
        START_PRELOAD_RESOURCES = "preloader_start_preload_resources"
        ADD_ITEM = "preloader_add_item"
        COMPLETED_ITEM = "preloader_completed_item"
        READY = "preloader_ready"
    end enum

    enum USER
        SET_ACTIVE_LANGUAGE_KEY = "user_set_active_language"
        SET_ACTIVE_THEME_KEY = "user_set_active_theme"
    end enum

    enum SLEEP
        START = "sleep_start"
        COMPLETED = "sleep_completed"
    end enum

    enum HTTP
        FETCH = "http_fetch"
    end enum

    enum CONTENT_READER
        START_LOADING = "CONTENT_READER_start_loading"
        FETCH_DATA = "CONTENT_READER_fetch_date"
        DATA_RECEIVED = "CONTENT_READER_data_received"
        REQUEST_ERROR = "CONTENT_READER_request_error"
    end enum

end namespace
