
namespace Models

    class AppStore extends Model

        state = {

            activePageKey: "home",
            loadingScreenMinTime: 0, ' sec

            pageList: [
                "home",
                ' "movies",
                ' "series",
                "zoomListSample",
                "playground",
                "settings"
            ],

            ' Available pages
            pageSettings: {
                home: {
                    enablePrerender: true,
                    enableKeepAlive: true
                },
                ' movies: {
                '     enablePrerender: false,
                '     enableKeepAlive: false
                ' },
                ' series: {
                '     enablePrerender: false,
                '     enableKeepAlive: false
                ' },
                zoomListSample: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                playground: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                settings: {
                    enablePrerender: false,
                    enableKeepAlive: true
                }
            }
        }


    end class

end namespace
