
namespace Reducers

    class AppStoreReducer extends Reducer

    sub logIntent(intent)
        print `[APP_STORE REDUCER][INFO] dispatcherId: ${m.ownerDispatcherId}, type: ${intent.type}`; intent?.payload?.activePageKey <> invalid ? `, activePageKey: ${intent.payload?.activePageKey}` : ""
    end sub

    override function applyMiddlewares()
        return [
            ' Logger middleware
            function(intent as Interface.Intent, state) as Interface.Intent
                m.logIntent(intent)
                return intent ' NEXT
            end function
        ]
    end function

        override function reducer(state, intent)

            if intent.type = IntentType.APP_STORE.SET_ACTIVE_PAGE_KEY
                state.activePageKey = intent.payload.activePageKey
            end if

            return state
        end function

    end class

end namespace
