
namespace Models

    class AppStore extends Model

        state = {

            activePageKey: "playground2",
            loadingScreenMinTime: 1.5, ' sec

            pageList: [
                "home",
                "movies",
                "series",
                "rowListExample",
                "zoomListSample",
                "playground1",
                "playground2",
                "settings"
            ],

            ' Available pages
            pageSettings: {
                home: {
                    enablePrerender: true,
                    enableKeepAlive: true
                },
                movies: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                series: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                rowListExample: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                zoomListSample: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                playground1: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                playground2: {
                    enablePrerender: false,
                    enableKeepAlive: false
                },
                settings: {
                    enablePrerender: false,
                    enableKeepAlive: true
                }
            }
        }


    end class

end namespace
