' Rotor Framework Task
import "pkg:/source/libs/rotorFramework/RotorFrameworkTask.bs"

' Import common contants
import "pkg:/components/app/common/intentTypes.bs"

' Import Models and Reducers
import "homeReader/homeReaderModel.bs"
import "homeReader/homeReaderReducer.bs"

' imoprt specific helpers
' import "../../common/httpLogic/createHttpDispatcher.bs"

sub init()
    m.top.functionName = "task"
    m.appFw = new Rotor.FrameworkTask()
end sub

sub task()

    ' * CREATE DISPATCHERS (Owned by this Task)

    ' Create home content reader dispatcher
    homeReaderModel = new Models.HomeReaderModel()
    homeReaderReducer = new Reducers.HomeReaderReducer()
    m.homeReaderDispatcher = new Dispatcher("homeReader", homeReaderModel, homeReaderReducer)

    m.appFw.sync() ' main loop of multi-thread MVI
end sub
